name: challenge

on: [push]

env:
  FILE_NAME: README.md
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v1

    - name: Upload an arbitrary artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ubuntu
        path: ./${{ env.FILE_NAME }}
