name: hello

on: push

jobs:
  test:
      name: Test python
      runs-on: ubuntu-latest
      steps:
      - name: Step one
        uses: actions/checkout@v4
      - name: Setup Python environment
        uses: actions/setup-python@v5
      - name: Step two
        run: python hello.py
